apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: skaffoldOQ
build:
  artifacts:
  - image: andyovch/sa-user
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployments/k8s/deployment.yaml
    - deployments/k8s/ingress.yaml
    - deployments/k8s/service.yaml
