apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
      - name: user
        image: andyovch/sa-user:0.0.3
        env:
        - name: USER_PORT
          valueFrom:
            configMapKeyRef:
              name: user-config
              key: service_port
        - name: USER_DBUSER
          valueFrom:
            configMapKeyRef:
              name: user-config
              key: db_user
        - name: USER_DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: db_password
        - name: USER_DBHOST
          valueFrom:
            configMapKeyRef:
              name: user-config
              key: db_host
        - name: USER_DBPORT
          valueFrom:
            configMapKeyRef:
              name: user-config
              key: db_port
        - name: USER_DBNAME
          valueFrom:
            configMapKeyRef:
              name: user-config
              key: db_name
        ports:
        - name: web
          containerPort: 8000
        livenessProbe:
          httpGet:
            port: web
            path: /health
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: web
            path: /ready
          initialDelaySeconds: 5
          periodSeconds: 5