apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "userchart.fullname" . }}-config
data:
  service_port: {{ .Values.service.port | quote }}
  db_host: {{ include "postgresql.fullname" . }}
  db_name: {{ .Values.postgresql.postgresqlDatabase }}
  db_user: {{ .Values.postgresql.postgresqlUsername }}
  db_port: {{ .Values.postgresql.service.port | quote }}