apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "userchart.fullname" . }}
  labels:
    {{- include "userchart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "userchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "userchart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        env:
        - name: USER_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ include "userchart.fullname" . }}-config
              key: service_port
        - name: USER_DBUSER
          valueFrom:
            configMapKeyRef:
              name: {{ include "userchart.fullname" . }}-config
              key: db_user
        - name: USER_DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "userchart.fullname" . }}-secret
              key: db_password
        - name: USER_DBHOST
          valueFrom:
            configMapKeyRef:
              name: {{ include "userchart.fullname" . }}-config
              key: db_host
        - name: USER_DBPORT
          valueFrom:
            configMapKeyRef:
              name: {{ include "userchart.fullname" . }}-config
              key: db_port
        - name: USER_DBNAME
          valueFrom:
            configMapKeyRef:
              name: {{ include "userchart.fullname" . }}-config
              key: db_name
        ports:
        - name: web
          containerPort: {{ .Values.service.port }}
        livenessProbe:
          httpGet:
            port: web
            path: /health
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: web
            path: /ready
          initialDelaySeconds: 5
          periodSeconds: 5