apiVersion: v1
kind: Service
metadata:
  name: {{ include "userchart.fullname" . }}
  labels:
    {{- include "userchart.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "userchart.selectorLabels" . | nindent 4 }}
  ports:
  - port: 8001
    targetPort: {{ .Values.service.port }}
    protocol: TCP
  type: {{ .Values.service.type }}